language: node_js
node_js:
  - 0.12.0
  - 4.1.1
  - stable
after_success:
  - npm run coveralls
before_deploy:
  - npm --no-git-tag-version version 1.0.$TRAVIS_BUILD_NUMBER
deploy:
  provider: npm
  email: chris@cns.me.uk
  api_key:
    secure: xllqJENU3rJf24e5rJB3oxn/Vuq2wAu2fU8gn6hjHwVNaxNGJ6YRZsVgJl1uW7CsmYXHQHS4+jgQU5CLEBX07RIf64P6beaho8dehv5LhlXqT5Oll8IXNnqXB9IFGoJ9X7mRHosp1o+M/qy47UOkxMTT1oJ5lcbJawfi3DqgNRl0q4eyLvbIkJCgLn9UrgIO87i4EwkhlmJzzo+0mmkdGzf/VT0mPFvSZaZSJS2PTpRa1maWt3ChYXp4WZQ009AiHMo0WkANfJ2qeB8aUleohNpR4scyKJ4ub8uxXFpDmmjZwNA6OWkBiFItvvPQE/WCPYqyd6s1t4t/0naawZ2z8BTnDa7RhE9ykPboE+feIdSW8i72fDHHgvpPOeqjt1/bJa1dw+CSllytqLYgKzBa9gefBS6meadrHQ/jjPu26AOHiJ3swOMEbRNbQ4e4PYRmi2tkEIUrNj8nB29AR08PxZysiy2pVC0fRqIfgsi9Ny8WwvBo3LYuwtH6N7ZMX8TgSavbJhvExFUw4WZD6qsFNNAtBUV0+kvKGbNZnQ02DzuPNx7DQN2RGFglhHjUNRzUeGutu2z0ohVsF0NlU0+k5rJ9lrEFiUcFEm9454WT3RWxizugTIDykfrI/mbdPmSCPVD0E6bSwS6uINgQKsUuB/zyTFK+hjUrzxXj5Ya6LBo=
  skip_cleanup: true
  on:
    repo: chrisns/passportjs-header
    branch: master
    node_js: stable
